# Data Handling and Computation
### Numpy Array

In [1]:
import numpy as np

# create array of 1D
arr = np.array([1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


In [2]:
# creating 2D array
arr_2d = np.array([[2,3],[4,5],[6,9]])
print(arr_2d)

# checking shape of array
print("Shape: ",arr_2d.shape)

[[2 3]
 [4 5]
 [6 9]]
Shape:  (3, 2)


In [3]:
# creating 3D array
arr_3d = np.array([[[1,2,3],[4,5,6],[4,1,2],[4,5,6]]])
print(arr_3d.shape)

# checking dim of array
print(arr_2d.ndim)


(1, 4, 3)
2


In [4]:
# creating another 3D array
arr_3d = np.arange(20)
arr_3d = arr_3d.reshape(2,2,5)
print(arr_3d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [5]:
# shape of arr_3d
print("Shape of arr_3d")
print('group, row, column: ', arr_3d.shape)

# indexing 3D arrays
print(arr_3d[0]) # first group
print(arr_3d[0][0]) # first row of the first group
print(arr_3d[0][0][0]) # first element of the first row of the first group

Shape of arr_3d
group, row, column:  (2, 2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
0


In [6]:
# slicing of arrays
arr = np.array([1,2,3,4,5,6,7])
print(arr[0:5:2])

# 2D array
arr_2d = np.array([[2,3],[4,5],[6,9]])
print(arr_2d[0:2])
print(arr_2d[0:2,1])

[1 3 5]
[[2 3]
 [4 5]]
[3 5]


In [7]:
import time

# creating range
arr1 = np.arange(1,11)

# creating 2D array
arr_2d = arr1.reshape(2,5)
print(arr_2d)

# 5 rows and 2 columns
arr_2dnew = arr_2d.reshape(5,2)
print(arr_2dnew)

# for iteration
for row in arr_2d:
    for element in row:
        print(element)
        time.sleep(0.5)

# Or we can convert nD array into a single 
for i in np.nditer(arr_2d):
    print(i)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10


In [8]:
# print index of values
for idx,i in np.ndenumerate(arr_2dnew):
    print(idx,i)

# splitting arrays
arr1 = np.arange(1,10)
print(np.split(arr1,3))

# method 2: For split array into any number
any_arr = np.array_split(arr1,4)
print(any_arr)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
(2, 0) 5
(2, 1) 6
(3, 0) 7
(3, 1) 8
(4, 0) 9
(4, 1) 10
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [9]:
# creating 2d array
a = np.array([[1,1],[2,2],[3,3]])
print(a)

# insert in a column
a = np.insert(a,1,5,axis=1) # np.insert(array,position,value,axis)
print(a)

[[1 1]
 [2 2]
 [3 3]]
[[1 5 1]
 [2 5 2]
 [3 5 3]]


In [10]:
# insert a column with each element different
a = np.array([[1,1],[2,2],[3,3]])
a = np.insert(a,1,[1,2,3],axis=1)
print("column inserted...\n", a)

column inserted...
 [[1 1 1]
 [2 2 2]
 [3 3 3]]


In [11]:
# append
a = np.append([1,2,3],[[4,5,6],[7,8,9]])
print(a)

# appending a 2d array
a = np.append([[1,2,3],[4,5,6]], [[7,8,9]], axis=0)
print(a)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# delete
x = np.arange(1,10).reshape(3,3)
print(x)
print(np.delete(x,2,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


### Numpy Advanced Function
* Randint
* Rand
* choice
* Data distribution
* Random permutation

In [13]:
import numpy as np
from numpy import random

x = random.randint(100) # to print any number btwn 0-99
print(x)

# print 2D array from above
x1 = random.randint(100,size=(3,3))
print(x1)

# print float values btw 0 to 1
fit_value = random.rand()
print(f"fit_value: {fit_value}")

# printing more than one value in above function
the_num = random.rand(3)
print(f"the_num: {the_num}")

95
[[45 63  1]
 [35 57 46]
 [80 14 25]]
fit_value: 0.39657589045152386
the_num: [0.04192114 0.38101805 0.93900825]


In [14]:
# from a list print any random element
output = random.choice([3,5,7,9])
print(output)
output = random.choice([3,5,7,9],size=(5,2)) # adding a specific size
print(output, "\n")
output = random.choice([3,5,7,9],size=(2,2))
print(output)


7
[[7 9]
 [7 9]
 [5 5]
 [7 5]
 [7 9]] 

[[5 5]
 [3 3]]


In [15]:
# data distribution

from numpy import random

choice = np.array([3,5,7,9])
x2 = random.choice(choice, p=[0.2,0.3,0.4,0.1], size=[2,2])
print(x2)

# random data permutations

# method 1: Original data permutated won't change
permut = np.array(choice)
check=random.permutation(permut)
print("\n",check)

# method 2: Original data will change
random.shuffle(choice)
print("\n",choice)


[[9 7]
 [5 5]]

 [3 7 9 5]

 [9 5 3 7]


### Numpy Advanced Operation II
* Arithmetic
* Reciprocal
* Transpose
* More operations

In [16]:
arr1 = np.arange(9,dtype=np.float_).reshape(3,3)
arr2 = np.array([10,10,10])
arr3 = np.array([10,11,12])

print("arr1: ",arr1,"\n","arr2:",arr2)
# Arithmetic ops
# adding
print('Addition:')
print(np.add(arr1, arr2))

# subtraction
print("Subtraction:")
print(np.subtract(arr1,arr2))

# multiplication
print('Multiplication:')
print(np.multiply(arr1,arr1))

# division
print('Division:')
print(np.divide(arr1,arr2))

# power
print("Power:")
print(np.power(arr1,arr2))

arr1:  [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]] 
 arr2: [10 10 10]
Addition:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
Subtraction:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]
Multiplication:
[[ 0.  1.  4.]
 [ 9. 16. 25.]
 [36. 49. 64.]]
Division:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
Power:
[[0.00000000e+00 1.00000000e+00 1.02400000e+03]
 [5.90490000e+04 1.04857600e+06 9.76562500e+06]
 [6.04661760e+07 2.82475249e+08 1.07374182e+09]]


In [17]:
# reciprocals in an array
a = np.array([0.25,1.2,1.,0.,100.])
print("Printing reciprocal...")
print(np.reciprocal(a))

Printing reciprocal...
[4.         0.83333333 1.                inf 0.01      ]


C:\Users\Cyriaque Matthews\AppData\Local\Temp\ipykernel_3380\2385691210.py:4: RuntimeWarning: divide by zero encountered in reciprocal
  print(np.reciprocal(a))


In [18]:
# transpose
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print("Original Matrix:")
print(arr_2d)
print("Transposed Matrix:")
print(arr_2d.T)

# unix matrix
print("\nUnix Matrix")
print(np.identity(3, dtype=int))

# other operations
print("Max value in matrix: ", np.amax(arr_2d))
print("Min value in matrix: ", np.amin(arr_2d))
print("Mean of matrix: ", np.mean(arr_2d))
print("Median of matrix: ", np.median(arr_2d))


Original Matrix:
[[1 2 3 4]
 [5 6 7 8]]
Transposed Matrix:
[[1 5]
 [2 6]
 [3 7]
 [4 8]]

Unix Matrix
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Max value in matrix:  8
Min value in matrix:  1
Mean of matrix:  4.5
Median of matrix:  4.5


#### Handling Matrices


In [19]:
from numpy import matrix as mtx

# creating matrix
# using strings
a = mtx('1,2;3,4')
print(a)
print(type(a))

# using arrays
b = mtx([[1,5],[6,7]])

# a big big one
mat1 = mtx('1,2,3,4;5,6,7,8;9,10,11,12;13,14,15,16')
print(mat1)

[[1 2]
 [3 4]]
<class 'numpy.matrix'>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [20]:
# operations
## checking dimensions
print("Dimensions: ",mat1.ndim)

## checking number of elements in matrix
print("Size: ", mat1.size)
# shape
print("Shape: ",mat1.shape)

# transpose
print(">> mat1.T")
print(mat1.T)
print(">> mat1")
print(mat1)
print(">> mat2=mat1.T")
mat2 = mat1.T
print(mat2)
print(">> mat2.base")
print(mat2.base)

Dimensions:  2
Size:  16
Shape:  (4, 4)
>> mat1.T
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
>> mat1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
>> mat2=mat1.T
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
>> mat2.base
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [21]:
# more matrix operations - Arithmetic
print('Addition of Matrices:')
print(np.add(mat1,mat2))
print("Square root of Matrix: ")
print(np.sqrt(mat1))
print("Addition via axis: ")
print(np.sum(mat1,axis=1))

Addition of Matrices:
[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]
Square root of Matrix: 
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]
 [3.60555128 3.74165739 3.87298335 4.        ]]
Addition via axis: 
[[10]
 [26]
 [42]
 [58]]


In [22]:
# max index value. Note it is different from max value; np.amax()
print(mat1.argmax())
# min index value
print(mat1.argmin())

# converting data type
print(mat2.astype(str))

print("mat2: ")
print(mat2)

# Clip method. Any number >3 is converted to 3 and
# any number <10 is converted to 10
print("Clipped! ")
print(np.clip(mat2,3,10)) 

15
0
[['1' '5' '9' '13']
 ['2' '6' '10' '14']
 ['3' '7' '11' '15']
 ['4' '8' '12' '16']]
mat2: 
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Clipped! 
[[ 3  5  9 10]
 [ 3  6 10 10]
 [ 3  7 10 10]
 [ 4  8 10 10]]


In [23]:
# compress method. Choosing which row/column to prin
print("By row compress:\n", np.compress([0,1,0,1], mat2, axis=0))
print("By column compress:\n", np.compress([0,1,0,1], mat2, axis=1))

# fill function
mat3 = mat2.copy()
mat3.fill(1.5)
print("mat3:\n",mat3)

By row compress:
 [[ 2  6 10 14]
 [ 4  8 12 16]]
By column compress:
 [[ 5 13]
 [ 6 14]
 [ 7 15]
 [ 8 16]]
mat3:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [24]:
print("mat1:")
print(mat1)

# cummulative product
print("Cummulative Prod:")
print(np.cumprod(mat1,axis=1))

# cummulative sum
print("Cummulative Sum:")
print(np.cumsum(mat1))

mat1:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Cummulative Prod:
[[    1     2     6    24]
 [    5    30   210  1680]
 [    9    90   990 11880]
 [   13   182  2730 43680]]
Cummulative Sum:
[[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136]]


In [25]:
# getting matrix diagonal
print(">> mat1 diag:")
print(mat1.diagonal())

# flipping matrix up down
print(">> Flip up down:")
print(np.flipud(mat1))

# flipping matrix left right
print(">> Print left right:")
print(np.fliplr(mat1))

>> mat1 diag:
[[ 1  6 11 16]]
>> Flip up down:
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
>> Print left right:
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [26]:
print(mat1)
mat1[2,3] = 100
print(mat1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11 100]
 [ 13  14  15  16]]


In [27]:
print(mat1[1:])
print(mat1[1:,2:])

[[  5   6   7   8]
 [  9  10  11 100]
 [ 13  14  15  16]]
[[  7   8]
 [ 11 100]
 [ 15  16]]


In [28]:
# maximum value on each row
print(mat1.max(1))

# minimum value on each column
print(mat1.min(0))

[[  4]
 [  8]
 [100]
 [ 16]]
[[1 2 3 4]]


In [29]:
# finding location of nonzero values in mat1
mat1.nonzero()

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [30]:
print(">> mat1:")
print(mat1)

print(">> Product of each row")
print(mat1.prod(1))

print(">> Product of each column")
print(mat1.prod(0))

>> mat1:
[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11 100]
 [ 13  14  15  16]]
>> Product of each row
[[   24]
 [ 1680]
 [99000]
 [43680]]
>> Product of each column
[[  585  1680  3465 51200]]


In [31]:
arr = mtx([1,2,3])
print("arr: ",arr)
print(type(arr))
r=2
print(mtx.repeat(arr,r))
print(mtx.repeat(arr,3))

arr:  [[1 2 3]]
<class 'numpy.matrix'>
[[1 1 2 2 3 3]]
[[1 1 1 2 2 2 3 3 3]]


# Data Mining
#### Web Scraping

In [32]:
import requests, time
# use requests module to connect website like a web browser
mywebsite = "https://lnbspace.github.io/"

# connecting to the web
page = requests.get(mywebsite)

# what are the functions under page var?
print("Functions under page var: ")
print(dir(page),"\n")
# checking http status code
if page.status_code == 200:
    print("My website ..", mywebsite, " is working fine")
    # print content
    print(page.content)

    # printing in better format
    print("\nNow in a better format: ")
    time.sleep(2)
    print(page.text) # better format
else:
    print("check your URL ...please")

Functions under page var: 
['__attrs__', '__bool__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__nonzero__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_content', '_content_consumed', '_next', 'apparent_encoding', 'close', 'connection', 'content', 'cookies', 'elapsed', 'encoding', 'headers', 'history', 'is_permanent_redirect', 'is_redirect', 'iter_content', 'iter_lines', 'json', 'links', 'next', 'ok', 'raise_for_status', 'raw', 'reason', 'request', 'status_code', 'text', 'url'] 

My website .. https://lnbspace.github.io/  is working fine
b'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <title>lnb</title>\n    <link rel="stylesheet" href="style.css">\n</head>\n<b

#### Webscraping

In [37]:
from bs4 import BeautifulSoup
url = "https://lnbspace.github.io/"

# connecting to web
page = requests.get(url)
print(page.content)

# scraping using bs4
soup = BeautifulSoup(page.content, "html5lib") # html5lib is a parser
# html5lib undertands tags of html
# parser list - html5lib, lxml, html.parser

print("\nPrinting `soup`...")
time.sleep(1)
print(soup)

# printing title only
print("\ntitle data is getting printed..")
time.sleep(1)
print(soup.title)
print("\nprinting the text now..")
time.sleep(1)
print(soup.title.text)

b'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <title>lnb</title>\n    <link rel="stylesheet" href="style.css">\n</head>\n<body>\n    <h1> Hello world </h1>\n    <h2> welcome to Learn and build </h2>\n    <h1> Hello Ashutoshh </h1>\n\n  <div class="lnbclass">\n\t <h1> this is AI the super future </h1>\n \t <h2>This is a heading in a div element</h2>\n  \t<p>This is some text in a div element.</p>\n  </div>\n  <div class="lnbai">\n\t <h1> this is AI </h1>\n \t <h2>This is ashutoshh </h2>\n  \t<p>We are building future ...</p>\n  </div>\n</body>\n\n</html>\n'

Printing `soup`...
<!DOCTYPE html>
<html lang="en"><head>
    <title>lnb</title>
    <link href="style.css" rel="stylesheet"/>
</head>
<body>
    <h1> Hello world </h1>
    <h2> welcome to Learn and build </h2>
    <h1> Hello Ashutoshh </h1>

  <div class="lnbclass">
	 <h1> this is AI the super future </h1>
 	 <h2>This is a heading in a div element</h2>
  	<p>This is some text in a div element.</p>
  </div>
  <div class="lnbai">


In [34]:
# printing head tag
print(soup.head.text)
# printing body tag
print(soup.body)
print("\nNow the text: ")
time.sleep(1)
print(soup.body.text)



    lnb
    

<body>
    <h1> Hello world </h1>
    <h2> welcome to Learn and build </h2>
    <h1> Hello Ashutoshh </h1>

  <div class="lnbclass">
	 <h1> this is AI the super future </h1>
 	 <h2>This is a heading in a div element</h2>
  	<p>This is some text in a div element.</p>
  </div>
  <div class="lnbai">
	 <h1> this is AI </h1>
 	 <h2>This is ashutoshh </h2>
  	<p>We are building future ...</p>
  </div>



</body>

Now the text: 

     Hello world 
     welcome to Learn and build 
     Hello Ashutoshh 

  
	  this is AI the super future 
 	 This is a heading in a div element
  	This is some text in a div element.
  
  
	  this is AI 
 	 This is ashutoshh 
  	We are building future ...
  






#### Parsing Tag Based Data

In [47]:
# selecting h1 tag only
h1_data = soup.select('h1')
print("printing h1 tag data ...")
time.sleep(1)
print(h1_data)

# printing only first h1 data
print("printing only first h1 data")
time.sleep(1)
print(h1_data[0])

# printing all h1 tag data
time.sleep(2)
for data in h1_data:
    print(data.text)

printing h1 tag data ...
[<h1> Hello world </h1>, <h1> Hello Ashutoshh </h1>, <h1> this is AI the super future </h1>, <h1> this is AI </h1>]
printing only first h1 data
<h1> Hello world </h1>
 Hello world 
 Hello Ashutoshh 
 this is AI the super future 
 this is AI 


In [51]:
# storing in a list
list_data = []

for data in h1_data:
    print(data.text)
    list_data.append(data.text)

print("printing data in a single list", list_data)

# storing data in a file
f1 = open("myh1data.txt", 'w')

for data in h1_data:
    f1.write(data.text)

 Hello world 
 Hello Ashutoshh 
 this is AI the super future 
 this is AI 
printing data in a single list [' Hello world ', ' Hello Ashutoshh ', ' this is AI the super future ', ' this is AI ']
