# Data Handling and Computation
### Numpy Array

In [1]:
import numpy as np

# create array of 1D
arr = np.array([1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


In [3]:
# creating 2D array
arr_2d = np.array([[2,3],[4,5],[6,9]])
print(arr_2d)

# checking shape of array
print("Shape: ",arr_2d.shape)

[[2 3]
 [4 5]
 [6 9]]
Shape:  (3, 2)


In [4]:
# creating 3D array
arr_3d = np.array([[[1,2,3],[4,5,6],[4,1,2],[4,5,6]]])
print(arr_3d.shape)

# checking dim of array
print(arr_2d.ndim)


(1, 4, 3)
2


In [9]:
# creating another 3D array
arr_3d = np.arange(20)
arr_3d = arr_3d.reshape(2,2,5)
print(arr_3d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [11]:
# shape of arr_3d
print("Shape of arr_3d")
print('group, row, column: ', arr_3d.shape)

# indexing 3D arrays
print(arr_3d[0]) # first group
print(arr_3d[0][0]) # first row of the first group
print(arr_3d[0][0][0]) # first element of the first row of the first group

Shape of arr_3d
group, row, column:  (2, 2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
0


In [9]:
# slicing of arrays
arr = np.array([1,2,3,4,5,6,7])
print(arr[0:5:2])

# 2D array
arr_2d = np.array([[2,3],[4,5],[6,9]])
print(arr_2d[0:2])
print(arr_2d[0:2,1])

[1 3 5]
[[2 3]
 [4 5]]
[3 5]


In [18]:
import time

# creating range
arr1 = np.arange(1,11)

# creating 2D array
arr_2d = arr1.reshape(2,5)
print(arr_2d)

# 5 rows and 2 columns
arr_2dnew = arr_2d.reshape(5,2)
print(arr_2dnew)

# for iteration
for row in arr_2d:
    for element in row:
        print(element)
        time.sleep(0.5)

# Or we can convert nD array into a single 
for i in np.nditer(arr_2d):
    print(i)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10


In [25]:
# print index of values
for idx,i in np.ndenumerate(arr_2dnew):
    print(idx,i)

# splitting arrays
arr1 = np.arange(1,10)
print(np.split(arr1,3))

# method 2: For split array into any number
any_arr = np.array_split(arr1,4)
print(any_arr)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
(2, 0) 5
(2, 1) 6
(3, 0) 7
(3, 1) 8
(4, 0) 9
(4, 1) 10
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [26]:
# creating 2d array
a = np.array([[1,1],[2,2],[3,3]])
print(a)

# insert in a column
a = np.insert(a,1,5,axis=1) # np.insert(array,position,value,axis)
print(a)

[[1 1]
 [2 2]
 [3 3]]
[[1 5 1]
 [2 5 2]
 [3 5 3]]


In [29]:
# insert a column with each element different
a = np.array([[1,1],[2,2],[3,3]])
a = np.insert(a,1,[1,2,3],axis=1)
print("column inserted...\n", a)

column inserted...
 [[1 1 1]
 [2 2 2]
 [3 3 3]]


In [31]:
# append
a = np.append([1,2,3],[[4,5,6],[7,8,9]])
print(a)

# appending a 2d array
a = np.append([[1,2,3],[4,5,6]], [[7,8,9]], axis=0)
print(a)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
# delete
x = np.arange(1,10).reshape(3,3)
print(x)
print(np.delete(x,2,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
